apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: aguante-el-rojo-pipeline
spec:
  tasks:
    - name: aguante-el-rojo-task
      taskRef:
        kind: Task
        name: aguante-el-rojo-task
